annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.0.0
dependencies:
  - name: common
    repository: https://openchart.choerodon.com.cn/choerodon/c7n
    version: 1.x.x
description: Gitlab service of Choerodon.
engine: gotpl
home: https://github.com/open-hand/gitlab-service/tree/master/chart/gitlab-service
icon: https://ui-avatars.com/api/?name=gitlab-service
keywords:
  - choerodon
  - gitlab
maintainers:
  - email: zhuchiyu@vip.hand-china.com
    name: choerodon
    url: https://choerodon.io
name: gitlab-service
sources:
  - https://github.com/open-hand/gitlab-service
  - https://gitee.com/open-hand/gitlab-service
version: 2.0.0
